name: test

on:
  push:
    branches:
      - 'main'
  pull_request:
    branches:
      - 'main'
    types:
      - 'opened'
      - 'synchronize'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      #----------------------------------------------
      #       check-out repo and set-up python
      #----------------------------------------------
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up python
        id: setup-python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11.0'
          cache: 'poetry'

      - name: Install Poetry
        uses: snok/install-poetry@v1

      - name: Install project
        run: poetry install --no-interaction

      - name: Run tests
        run: |
          poetry run flake8 dji_parse/
          poetry run black dji_parse/
          poetry run pytest tests/
